# Site settings
baseurl = "https://www.artacode.com/"
#baseurl = "artacode.com"
languageCode = "en"
title = "一二三四吾"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-123407925-1"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = true
[params]
	author = "Argericy"
	description = "想成为一名艺术家的码农"
	bio = "Argericy"

	twitter = "your_twitter_id"
	facebook = "your_facebook_id"

	enableRSS = true
	enableToc = true

	enableDisqus = false
	enableComment = true
	disqusShortname = "yun-xi-de-bo-ke"


	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false


	enableGoogleAnalytics = true
	enableBaiduAnalytics = true
	# Set the value to your baidu analysis code if you want to use baidu analytics
	baiduAnalytics = '118e166eca53816aaead0948042f2989'

	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
	#facebook-square = "https://www.facebook.com/nodejh"
	#twitter-square = "https://www.twitter.com/nodejh"
	github-square = "https://github.com/yunxi177"
